name: Deploy to EC2
# masterにpushされた時にjobを実行する
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SECRET_KEY }}
          USER_NAME: ${{ secrets.EC2_USER }}
          HOST_NAME: ${{ secrets.EC2_HOST }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} 'cd /usr/share/nginx/html/myapp/qa_allocation && git pull origin master'
